### ISSUE TITLE
failed to run docker-compose in detailed mode 

### ISSUE THREAD

**Issue by khzhu** [miso-lims/miso-lims#1893]
I got following errors when tried to lunch the detailed sample demo with docker-compose. Please let me know how to get it fixed, thank you!

Status: Downloaded newer image for misolims/miso-lims-webapp:latest
Creating miso-lims_db_1 ... done
Creating miso-lims_flyway_1 ... done
Creating miso-lims_webapp_1 ... error

ERROR: for miso-lims_webapp_1  Cannot start service webapp: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/local/miso-lims/.docker/detailed_sample_config/miso.properties\\\" to rootfs \\\"/var/lib/docker/overlay2/1887b37f5b9d0f9c9ffb7fac01cc61ec88474e8d2fbe16f12d576a7eb7255ace/merged\\\" at \\\"/var/lib/docker/overlay2/1887b37f5b9d0f9c9ffb7fac01cc61ec88474e8d2fbe16f12d576a7eb7255ace/merged/usr/local/tomcat/conf/Catalina/localhost/miso.properties\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for webapp  Cannot start service webapp: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/local/miso-lims/.docker/detailed_sample_config/miso.properties\\\" to rootfs \\\"/var/lib/docker/overlay2/1887b37f5b9d0f9c9ffb7fac01cc61ec88474e8d2fbe16f12d576a7eb7255ace/merged\\\" at \\\"/var/lib/docker/overlay2/1887b37f5b9d0f9c9ffb7fac01cc61ec88474e8d2fbe16f12d576a7eb7255ace/merged/usr/local/tomcat/conf/Catalina/localhost/miso.properties\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by morgantaschuk** [comment]
Hi @khzhu . Can you post the command you're using to launch docker-compose?

Looking at the error message, it says `\"/usr/local/miso-lims/.docker/detailed_sample_config/miso.properties caused \"not a directory\""": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type` which makes me think there might be a problem with your docker-compose command.

**Comment by khzhu** [comment]
Hi @morgantaschuk , here is the command I used. thanks!

> export MISO_DB_USER=tgaclims MISO_DB=lims MISO_DB_PASSWORD_FILE=./.miso_db_password MISO_TAG=latest
docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.detailed.yml up

**Comment by morgantaschuk** [comment]
Thanks! A few more questions I should have asked. 

What operating system are you using? There's some [other docs](https://github.com/Microsoft/WSL/issues/1854) that say Docker for Windows has slightly different behaviour than we expect. 

Can you post the output of running `cat .docker/detailed_sample_config/miso.properties` where you're launching the command from? We found [this](https://stackoverflow.com/questions/45972812/are-you-trying-to-mount-a-directory-onto-a-file-or-vice-versa) that said that there's a chance the file is being read as a directory instead of a file.

If you want, we can take this discussion either to the [Gitter channel](https://gitter.im/TGAC/miso-lims) or to OICR's slack and talk about it in closer to realtime.

**Comment by morgantaschuk** [comment]
After talking with @khzhu in realtime, there were a few issues that we resolved together. 

First, we downloaded the contents of the `.docker` directory next to the yaml files so that it would have the miso.properties and other SQL files.

```
wget https://github.com/miso-lims/miso-lims/archive/master.zip && unzip master.zip 'miso-lims-master/.docker/*' && mv miso-lims-master/.docker . && rm -r master.zip miso-lims-master/
```

Then she ran into SQL errors, which occurred because the docker volumes in the compose files remembered previous failed attempts at starting MISO. *shakes fist*. After purging the local volumes and combining all of the compose files into one, we got it working for her.

```
docker-compose down && docker volume prune -f
```

And the complete `docker-compose-ready.yml` file:

```
version: '3.7'

# .env file or shell environment variables should contain the following: 
# MISO_DB_USER : name of the MySQL user who accesses MISO_DB [tgaclims]
# MISO_DB : name of the LIMS Db in MySql [lims]
# MISO_DB_PASSWORD_FILE : path to the file with the password to the MySQL DB for user MISO_DB_USER
# MISO_TAG : tag of the MISO Docker containers (migration and webapp)
# echo "changeme" > ./.miso_db_password && export MISO_DB_USER=tgaclims && export MISO_DB=lims && export MISO_DB_PASSWORD_FILE=./.miso_db_password && MISO_TAG=latest


secrets:
  lims_password: 
    file: ${MISO_DB_PASSWORD_FILE}

services:
  db:
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MISO_DB}
      MYSQL_USER: ${MISO_DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/lims_password
    secrets:
      - lims_password
    volumes:
      - "misolims_db:/var/lib/mysql"

  flyway:
    image: misolims/miso-lims-migration:${MISO_TAG}
    secrets:
      - lims_password
    links:
      - db
    depends_on:
      - db
    volumes:
      - "./.docker/detailed_sample_config:/flyway/migrations"


  webapp:
    image: misolims/miso-lims-webapp:${MISO_TAG}
    restart: always
    ports: 
      - "8090:8080"
    secrets:
      - lims_password
    links:
      - db
    depends_on:
      - db
    volumes:
      - ".docker/detailed_sample_config/miso.properties:/usr/local/tomcat/conf/Catalina/localhost/miso.properties"
      - "misolims_files:/storage/miso/files/"

volumes:
  misolims_db:
  misolims_files: 
```

I'm going to make a new FAQ section with common Docker problems and re-think the organisation of the compose files to make this slightly easier.
