### ISSUE TITLE
bind customized jsp to container failed

### ISSUE THREAD

**Issue by ray1919** [miso-lims/miso-lims#1934]
I want to customize some page, I use the volume bind feature as follow
```
      - type: bind
        source: "./detailed_sample_config/footer.jsp"
        target: "/usr/local/tomcat/webapps/ROOT/WEB-INF/footer.jsp"
```

when I compose up the website, the `WEB-INF` dir has only one file(footer.jsp), website 404 not found. I did the same as `miso.properties`, but what is wrong?

**Comment by djcooke** [comment]
We don't recommend this approach as it seems to interfere with Tomcat's ability to deploy the webapp normally. Another option would be to checkout out the source code (preferably a release tag), make the changes you'd like, and follow the instructions under "Building and running from source" in the Compose Install Guide: https://miso-lims.github.io/miso-lims/adm/compose-installation-guide.html

**Comment by djcooke** [comment]
To be a little more specific, you'd want to remove the `services > webapp > image` config in your docker-compose, and add the following under `services > webapp`:

```
build:
  context: .
  target: webapp
```

Then do `docker-compose build && docker-compose up`

**Comment by morgantaschuk** [comment]
Another option is to extend our Docker container to unpack the MISO war file before startup, which allows you to override anything on the path.

Create a Dockerfile in the local directory with the following:

```
FROM misolims/miso-lims-webapp:latest AS ray1919-miso-build

RUN mkdir ${CATALINA_HOME}/webapps/ROOT && unzip ${CATALINA_HOME}/webapps/ROOT.war -d ${CATALINA_HOME}/webapps/ROOT && rm ${CATALINA_HOME}/webapps/ROOT.war
```

Then in your compose file, amend the `webapp` container to use this Dockerfile. Your footer should work then.

```
  webapp:
    build:
      context: .
      target: ray1919-miso-build
    restart: always
    secrets:
      - lims_password
    links:
      - db
    depends_on:
      - db
    volumes:
      - type: bind
        source: "./detailed_sample_config/footer.jsp"
        target: "/usr/local/tomcat/webapps/ROOT/WEB-INF/footer.jsp"
```

You'll have to run `docker-compose -f <compose.yml> build && docker-compose -f <compose.yml> up`
