### ISSUE TITLE
Pinery fails to obtain JDBC connection with MySQL 5.7.25 running in Docker

### ISSUE THREAD

**Issue by peterk87** [miso-lims/miso-lims#2695]
Hello,

I compiled and installed [MISO Pinery](https://github.com/miso-lims/miso-lims/tree/develop/pinery-miso), but it doesn't seem to be able to communicate with the MISO MySQL DB running via Docker Compose on the same machine. The MISO DB running container logs "Bad handshake" whenever an unsuccessful request is made via Pinery.

Below is an HTTP 500 error response when trying to get sample info from Pinery with [httpie](https://github.com/httpie/httpie):

```
$ http :8080/pinery/sample/SAM12
HTTP/1.1 500
Connection: close
Content-Type: application/json
Date: Tue, 09 Aug 2022 21:25:49 GMT
Transfer-Encoding: chunked

{
    "data": {
        "exceptionClass": "org.springframework.jdbc.CannotGetJdbcConnectionException"
    },
    "detail": "Failed to obtain JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure\n\nThe last packet successfully received from the server was 5 milliseconds ago.  The last packet sent successfully to the server was 4 milliseconds ago.",
    "message": "Internal Server Error",
    "status": 500
}
```
Error message:
```
Failed to obtain JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 5 milliseconds ago.  The last packet sent successfully to the server was 4 milliseconds ago.
```

The `/var/lib/tomcat9/conf/Catalina/localhost/pinery-miso.properties` contains the correct `miso.db` values and the correct full file path to `pinery-miso.properties` is specified in `/var/lib/tomcat9/conf/Catalina/localhost/pinery.xml`. `/var/lib/tomcat9/webapps` contains a `pinery/` directory and `pinery.war` file.

---

MISO Docker `compose.yml`:

```yaml
secrets:
  lims_password:
    file: ${MISO_DB_PASSWORD_FILE}
  ssl_password:
    file: ${SSL_PASSWORD_FILE}

services:
  db:
    image: mysql:5.7.25
    ports:
      - "3306:3306"
    volumes:
      - type: "bind"
        source: "./db"
        target: "/var/lib/mysql"
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MISO_DB}
      MYSQL_USER: ${MISO_DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/lims_password
    secrets:
      - lims_password
  ...etc...
```
---

I even trying to connect to and query the DB in a Clojure/[Babashka](https://github.com/babashka/babashka) REPL, but it didn't work and I got a similar error message as making a request to Pinery:

```clojure
user=> (def conn {:dbtype "mysql" :user "MISO_DB_USER" :password "lims_password"})
#'user/conn
user=> (mysql/execute! conn ["show databases;"])
clojure.lang.ExceptionInfo: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. [at <repl>:50:1]
```

An [example script](https://github.com/babashka/pod-registry/blob/master/examples/mysql.clj) worked fine when running MySQL in Docker with `docker run --rm --name=test-mysql -p 3306:3306 -i --env="MYSQL_ROOT_PASSWORD=mypassword" mysql`, but it connects with the `root` user and password.

---

Is Pinery compatible with MISO running with Docker Compose?

Should I be using different credentials to access the MISO MySQL DB with Pinery?

Any help with getting Pinery working would be much appreciated!

Thanks!
